# Generated by Django 6.0.3 on 2026-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=50)),
                ('porte', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='pets/')),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
