# Generated by Django 6.0.3 on 2026-08-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoadocao',
            name='nome_pet',
        ),
        migrations.AddField(
            model_name='solicitacaoadocao',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='adocao.pet'),
        ),
    ]
